import json
from pathlib import Path

from knowledge.output.final_output_builder import (
    FinalOutputBuilder,
)


# ============================================================
# TEST CONFIGURATION
# ============================================================

PROGRAM_ID = "0001"

INPUT_FILE = Path(
    "data/0001/knowledge/normalized_program_facts.json"
)

OUTPUT_DIRECTORY = Path(
    "final"
)


# ============================================================
# HELPER FUNCTIONS
# ============================================================

def print_separator() -> None:
    print()
    print("=" * 80)


def validate_json_files(
    output_files: dict,
) -> None:
    """
    Verify that every generated output file:
    - exists;
    - contains valid JSON;
    - can be loaded successfully.
    """

    print_separator()
    print("VALIDATING GENERATED JSON FILES")
    print("=" * 80)

    validation_errors = []

    for section, file_path in output_files.items():

        path = Path(file_path)

        if not path.exists():

            validation_errors.append(
                f"{section}: File does not exist: {path}"
            )

            print(
                f"[FAIL] {section:<20} "
                f"File not found"
            )

            continue

        try:

            with path.open(
                "r",
                encoding="utf-8",
            ) as file:

                json.load(file)

            print(
                f"[PASS] {section:<20} "
                f"Valid JSON"
            )

        except json.JSONDecodeError as error:

            validation_errors.append(
                f"{section}: Invalid JSON: {error}"
            )

            print(
                f"[FAIL] {section:<20} "
                f"Invalid JSON"
            )

    if validation_errors:

        print_separator()

        print(
            f"JSON validation failed with "
            f"{len(validation_errors)} error(s)."
        )

        for error in validation_errors:

            print(
                f"- {error}"
            )

        raise AssertionError(
            "One or more generated files contain invalid JSON."
        )


def print_section_counts(
    section_counts: dict,
) -> None:
    """
    Print the number of facts assigned to each final section.
    """

    print_separator()
    print("FINAL OUTPUT SECTIONS")
    print("=" * 80)
    print()

    populated_sections = {
        section: count
        for section, count
        in section_counts.items()
        if count > 0
    }

    empty_sections = {
        section: count
        for section, count
        in section_counts.items()
        if count == 0
    }

    for section, count in populated_sections.items():

        print(
            f"{section:<25} "
            f"{count:>5} facts"
        )

    if empty_sections:

        print()
        print(
            f"Empty sections not written: "
            f"{len(empty_sections)}"
        )


def print_generated_files(
    output_files: dict,
) -> None:
    """
    Print all files generated by FinalOutputBuilder.
    """

    print_separator()
    print("GENERATED FILES")
    print("=" * 80)
    print()

    for section, file_path in output_files.items():

        print(
            f"{section:<25} "
            f"{file_path}"
        )


def validate_fact_coverage(
    summary: dict,
) -> None:
    """
    Verify that no unique normalized fact was silently dropped.

    Exact duplicates may be removed intentionally, but every unique
    fact must either:
    - be written to a known final section; or
    - be written to unhandled_data.json.
    """

    input_count = summary[
        "input_fact_count"
    ]

    unique_count = summary[
        "unique_fact_count"
    ]

    duplicate_count = summary[
        "exact_duplicate_count"
    ]

    handled_count = summary[
        "handled_fact_count"
    ]

    unhandled_count = summary[
        "unhandled_fact_count"
    ]

    written_count = summary[
        "written_fact_count"
    ]

    dropped_count = summary[
        "dropped_fact_count"
    ]

    print_separator()
    print("FACT COVERAGE")
    print("=" * 80)
    print()

    print(
        f"Input facts             : {input_count}"
    )

    print(
        f"Unique facts            : {unique_count}"
    )

    print(
        f"Exact duplicates removed: {duplicate_count}"
    )

    print(
        f"Handled facts           : {handled_count}"
    )

    print(
        f"Unhandled facts         : {unhandled_count}"
    )

    print(
        f"Written facts           : {written_count}"
    )

    print(
        f"Dropped facts           : {dropped_count}"
    )

    # Every unique fact must be accounted for.
    assert (
        handled_count
        + unhandled_count
        == unique_count
    ), (
        "Fact accounting mismatch: handled facts plus "
        "unhandled facts does not equal unique facts."
    )

    assert (
        written_count
        == unique_count
    ), (
        "Fact coverage failed: not every unique fact "
        "was included in the final output."
    )

    assert (
        dropped_count
        == 0
    ), (
        f"FinalOutputBuilder dropped "
        f"{dropped_count} fact(s)."
    )

    print()
    print(
        "[PASS] Every unique normalized fact was preserved."
    )


# ============================================================
# MAIN TEST
# ============================================================

def main() -> None:

    print_separator()
    print("FINAL OUTPUT BUILDER TEST")
    print("=" * 80)

    print()
    print(
        f"Program ID      : {PROGRAM_ID}"
    )

    print(
        f"Input file      : {INPUT_FILE}"
    )

    print(
        f"Output directory: {OUTPUT_DIRECTORY}"
    )

    # --------------------------------------------------------
    # Validate input
    # --------------------------------------------------------

    if not INPUT_FILE.exists():

        raise FileNotFoundError(
            "\n"
            f"Normalized facts file was not found:\n"
            f"{INPUT_FILE}\n\n"
            "Check the actual location and update INPUT_FILE "
            "in test_final_output_builder.py."
        )

    # --------------------------------------------------------
    # Create builder
    # --------------------------------------------------------

    builder = FinalOutputBuilder(

        output_directory=OUTPUT_DIRECTORY,

        # Do not generate files for categories that currently
        # contain no extracted facts.
        write_empty_files=False,

        indent=2,
    )

    # --------------------------------------------------------
    # Build final output
    # --------------------------------------------------------

    result = builder.build_from_file(

        input_file=INPUT_FILE,

        program_id=PROGRAM_ID,

        # Leave this as None.
        # The builder will find the programme name from
        # identity.program_name or identity.programme_name.
        program_name=None,

        write_files=True,
    )

    summary = result[
        "summary"
    ]

    output_files = result[
        "output_files"
    ]

    # --------------------------------------------------------
    # Print results
    # --------------------------------------------------------

    print_separator()
    print("BUILD RESULT")
    print("=" * 80)
    print()

    print(
        f"Status       : "
        f"{summary['status']}"
    )

    print(
        f"Program ID   : "
        f"{summary['program_id']}"
    )

    print(
        f"Program name : "
        f"{summary['program_name']}"
    )

    print_section_counts(
        summary[
            "section_fact_counts"
        ]
    )

    print_generated_files(
        output_files
    )

    # --------------------------------------------------------
    # Validate coverage
    # --------------------------------------------------------

    validate_fact_coverage(
        summary
    )

    # --------------------------------------------------------
    # Validate generated JSON
    # --------------------------------------------------------

    validate_json_files(
        output_files
    )

    # --------------------------------------------------------
    # Show unhandled facts
    # --------------------------------------------------------

    unhandled_facts = result[
        "unhandled_facts"
    ]

    if unhandled_facts:

        print_separator()
        print("UNHANDLED FACTS")
        print("=" * 80)
        print()

        for fact in unhandled_facts:

            print(
                f"[{fact['category']}] "
                f"{fact['field']} "
                f"= "
                f"{fact['value']}"
            )

    # --------------------------------------------------------
    # Final result
    # --------------------------------------------------------

    print_separator()

    print(
        "[PASS] Final output build completed successfully."
    )

    print(
        "[PASS] All generated files contain valid JSON."
    )

    print(
        "[PASS] No unique normalized facts were dropped."
    )

    print("=" * 80)
    print()


if __name__ == "__main__":

    main()